### ISSUE TITLE
Support for new mutate_all, mutate_at and mutate_if

### ISSUE THREAD

**Issue by jlegewie** [mdsumner/spdplyr#10]
dplyr 0.5.0 replaced `mutate_each` and `summarise_each` with a set of functions called `mutate_all`, `mutate_at` and `mutate_if` (and `summarise_all`, `summarise_at` and `summarise_if` or summarize_...). It would be great if spdplyr would support these functions.

**Comment by mdsumner** [comment]
Sounds good I'll have a look. If you want to write some tests that should
pass the changes that would really help

**Comment by jlegewie** [comment]
Here is a test set for `mutate_*`...

```
library("maptools")
library("spdplyr")

data(wrld_simpl)

test_that("Test 'mutate_all', 'mutate_at', 'mutate_if' functions", {
    # test 'mutate_all'
    d <- wrld_simpl %>%
        mutate_all(funs(as.character))
    expect_true(is.character(d$AREA) & is.character(d$FIPS) & is.character(d$POP2005))
    # test 'mutate_at'
    d <- wrld_simpl %>%
        mutate_at(vars(starts_with("L")), funs(as.integer))
    expect_true(is.integer(d$LON) & is.integer(d$LAT))
    # test 'mutate_if'
    d <- wrld_simpl %>%
        mutate_if(is.integer, funs(as.numeric))
    expect_false(is.integer(d$AREA) | is.integer(d$REGION)  | is.integer(d$UN))
})
```

**Comment by mdsumner** [comment]
Thanks for the test suite, but none of these functions are generics in dplyr, so there's really no way to add methods for Spatial (or anything else). I don't understand why this is? @hadley am I missing something here? 

I could do 

``` R
mutate_all <- function(x, ...) UseMethod("mutate_all")

mutate_all.default <- dplyr::mutate_all
```

 and add methods from there, but that could clash with other package's approaches, and especially if there are S4 setGeneric("mutate_all") implementations out there.

**Comment by mdsumner** [comment]
I was thinking that it might make sense to check if mutate_all is not already an S3 generic, then create if needed and add this method. That leaves us with adding data.frame method which would run dplyr::mutate_all, and possibly avoid stomping on any S4 generics.

**Comment by jlegewie** [comment]
Maybe @lionel- has some thoughts? I think he helped with these functions...

**Comment by lionel-** [comment]
I'm not sure but I think implementing methods for `mutate_()`, `summarise_()` and `tbl_vars()` is all that's required to make it work with another data type.

**Comment by jlegewie** [comment]
Yes, that's what I thought. But I think a method for `dplyr::groups` is also necessary. With the two methods below, `mutate_all` and `mutate_at` work but `mutate_if` still doesn't. I think the problem is `dplyr:::probe_colwise_names` (which calls `vapply`)...  

```
library("maptools")
library("spdplyr")

data(wrld_simpl)

tbl_vars.SpatialPolygonsDataFrame <- function(x) names(x)
groups.SpatialPolygonsDataFrame <- function(x) NULL

wrld_simpl %>% mutate_all(funs(as.character))
wrld_simpl %>% mutate_at(vars(starts_with("L")), funs(as.integer))
```

**Comment by lionel-** [comment]
The `_if()` variants do not work with databases either.

The easy fix is to make `probe_colwise_names()` an exported generic.  I'm not sure we want to abstract out function mapping in the dplyr interface though. So I don't know what can be done here.

Maybe have a generic map in purrr. I think we need a `s3map()` family in purrr. But until purrr depends on dplyr (there are plans to decouple) we can't have dplyr depend on purrr anyway.

What do you think @hadley?

**Comment by hadley** [comment]
Can you file an issue over in dplyr, and I'll make sure to think about it when I'm next working on dplyr.

**Comment by jlegewie** [comment]
Done. @mdsumner, maybe the best way is to support `*_all` and `*_at` now and add `*_at` later depending on that happens with dplyr. The two methods for `tbl_vars` and `groups` should do it.

**Comment by mdsumner** [comment]
@jlegewie @lionel- hi, I appreciate the input here and I'll do it if I can. Just want to let you know I now never use this package, I dplyr and pipe happily with https://github.com/r-gris/rangl and https://github.com/mdsumner/spbabel - there's a lot more to do but I'm just not that interested in sp anymore, it's way too limiting. I think normal forms (what spbabel::map_table does to Spatial) are more interesting and useful. I cast those to sp or whatever when needed, and new analyses and plotting are better done from the map_table-s.  I'll do the same for sf and eventually raster, I don't see them getting more general than they are already.  The new read ability in sf opens up all the Z-M simple features now and better builds on Windows for rgdal2 should open up a lot of formats, so there's no real need to focus on sp any more.

**Comment by jlegewie** [comment]
Thanks for the package recommendations. I will check them out when I find some time...

**Comment by mdsumner** [comment]
@jlegewie 

thanks again for this, I've finally had a closer look. It works for some examples, but not your more complex one. 

```
wrld_simpl %>% mutate_at(vars(starts_with("L")), funs(as.integer))
```

This one does work though, so I think it's about @data being a tibble. 

```
data(spmap)
spmap %>% mutate_at(vars(starts_with("L")), funs(as.integer))

```

If I can fudge this by always forcing a tibble in @data I'll do that. It has implications for assumptions about drop = TRUE in rgdal::writeOGR but I've only seen one report of that problem in the wild. 

I just need to check compatibility with old and new dplyr but getting close to a release now

**Comment by mdsumner** [comment]
Update: these are definitely only going to work in the upcoming dplyr, so I think I'll put that on as a dependency.

**Comment by mdsumner** [comment]
These are now not going to work any more because of hard requirements in rlang - it seems mutate_al is ok but mutate_if and mutate_all are not. 

https://github.com/mdsumner/spdplyr/issues/20

@jlegewie 

For now I'll remove the examples and tests. Possibly I could add explict methods for each of the special verbs?

**Comment by mdsumner** [comment]
sorry, not going to do this - this package won't get more features any more
